[build]
builder = "NIXPACKS"
buildCommand = "npm ci --include=dev --cache /tmp/npm-cache && npm run build"

[deploy]
startCommand = "npx prisma db push && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
